### ISSUE TITLE
Boiler option not working

### ISSUE THREAD

**Issue by DominikGus** [LavermanJJ/home-assistant-solarfocus#40]
Had a previous installation but the upgrade to v3.0.0-beta2 failed.

So I tried a fresh installation of v3.0.0-beta2 but that is only working if I choose "heatpump vampair".
If I try to use the option "Biomass boiler therminator II touch" I get the error: "Unexpected error"
(yes, I tried the correct IP and not just the hostname)

![image](https://user-images.githubusercontent.com/114312590/232126993-6c41b95c-68b0-4d05-935c-3e206977d4b8.png)

**Comment by LavermanJJ** [comment]
Thanks for reporting. I'll look into it.

**Comment by LavermanJJ** [comment]
’’’

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.solarfocus.config_flow
Source: custom_components/solarfocus/config_flow.py:161
Integration: Solarfocus (documentation, issues) 
First occurred: 10:32:25 (1 occurrences) 
Last logged: 10:32:25

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/solarfocus/config_flow.py", line 207, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/solarfocus/config_flow.py", line 174, in validate_input
    client = Solarfocus(hass, data=data)
  File "/config/custom_components/solarfocus/config_flow.py", line 161, in __init__
    self.api = SolarfocusAPI(
  File "/usr/local/lib/python3.10/site-packages/pysolarfocus/__init__.py", line 71, in __init__
    self.buffers = self.__factory.buffer(system,buffer_count,api_version)
  File "/usr/local/lib/python3.10/site-packages/pysolarfocus/component_factory.py", line 52, in buffer
    buffer = TherminatorBuffer(input)._initialize(self.__modbus_connector)
  File "/usr/local/lib/python3.10/site-packages/pysolarfocus/components/buffer.py", line 25, in __init__
    super().__init__(address=address)
TypeError: Buffer.__init__() got an unexpected keyword argument 'address'

’’’

**Comment by LavermanJJ** [comment]
@DominikGus I've published a new beta version.

**Comment by DominikGus** [comment]
Working like a charm! Thank you!
