### ISSUE TITLE
Unknown error when selecting EcoTop

### ISSUE THREAD

**Issue by jegsgit** [LavermanJJ/home-assistant-solarfocus#77]
**Describe the bug**
after selecting EcoTop boiler an unknown error occurs and config flow stops.

Logs show

TypeError: 'NoneType' object is not subscriptable

**To Reproduce**
Select EcoTop

**Expected behavior**
Error should be handled

**Desktop (please complete the following information):**
 - Home assistant version: 2023.9.2 and prevuious
 - Solarfocus custom component version 4.0.1
 - Solarfocus firmware version 23.020

Log errors:

2023-09-17 08:01:41.330 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/solarfocus/config_flow.py", line 216, in async_step_user
return await self.async_step_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/solarfocus/config_flow.py", line 255, in async_step_component
CONF_BOILER: user_input[CONF_BOILER],
~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by lein1013** [comment]
I just hat a quick look - it seems EcoTop is missing in the config flow, when I compare with my forked version that I used for my EcoTop
![grafik](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/72338417/4417bbd9-80c6-434d-8e19-63e642fd4767)
(screenshot related to my fork https://github.com/lein1013/home-assistant-solarfocus)
currently I've to less time update my fork to the latest changes and test the latest updates
As long as I don't have a good idea who to bring the inverted door contact into the main branch - a pull request does not make sense
![grafik](https://github.com/LavermanJJ/home-assistant-solarfocus/assets/72338417/7e77be0f-8df3-473c-beb3-a40d3d10c056)

**Comment by LavermanJJ** [comment]
Thanks for reporting. Did the error occur on a fresh install or when updating?

**Comment by LavermanJJ** [comment]
I'll look into it

**Comment by jegsgit** [comment]
Great project, thank You !
I had 3.22 installed and used therminator
for readings from the ecotop but had frequent 
drop outs where I had to stop and restart
the modbus on the ecotop itself.
I am looking forward to use the real thing 😎
If it helps I can test updated code inserted 
via the file editor but I am not much of a programmer myself.
